// Exercise Library
export const FETCH_EXERCISES = 'EXERCISE_LIBRARY_FETCH_EXERCISES';
export const FETCH_EXERCISES_SUCCESS = 'EXERCISE_LIBRARY_FETCH_EXERCISES_SUCCESS';
export const FETCH_EXERCISES_FAILURE = 'EXERCISE_LIBRARY_FETCH_EXERCISES_FAILURE';

export const CREATE_EXERCISE = 'EXERCISE_LIBRARY_CREATE_EXERCISE';
export const CREATE_EXERCISE_SUCCESS = 'EXERCISE_LIBRARY_CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_FAILURE = 'EXERCISE_LIBRARY_CREATE_EXERCISE_FAILURE';

export const UPDATE_EXERCISE = 'EXERCISE_LIBRARY_UPDATE_EXERCISE';
export const UPDATE_EXERCISE_SUCCESS = 'EXERCISE_LIBRARY_UPDATE_EXERCISE_SUCCESS';
export const UPDATE_EXERCISE_FAILURE = 'EXERCISE_LIBRARY_UPDATE_EXERCISE_FAILURE';

export const DELETE_EXERCISE = 'EXERCISE_LIBRARY_DELETE_EXERCISE';
export const DELETE_EXERCISE_SUCCESS = 'EXERCISE_LIBRARY_DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAILURE = 'EXERCISE_LIBRARY_DELETE_EXERCISE_FAILURE';

export const SEARCH_EXERCISES = 'EXERCISE_LIBRARY_SEARCH_EXERCISES';
export const SEARCH_EXERCISES_SUCCESS = 'EXERCISE_LIBRARY_SEARCH_EXERCISES_SUCCESS';

export const SET_SELECTED_EXERCISE = 'EXERCISE_LIBRARY_SET_SELECTED_EXERCISE';
