// Students
export const FETCH_STUDENTS = 'TRAINER_FETCH_STUDENTS';
export const FETCH_STUDENTS_SUCCESS = 'TRAINER_FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'TRAINER_FETCH_STUDENTS_FAILURE';

export const SEARCH_STUDENTS = 'TRAINER_SEARCH_STUDENTS';
export const SEARCH_STUDENTS_SUCCESS = 'TRAINER_SEARCH_STUDENTS_SUCCESS';

// Routines
export const CREATE_ROUTINE = 'TRAINER_CREATE_ROUTINE';
export const CREATE_ROUTINE_SUCCESS = 'TRAINER_CREATE_ROUTINE_SUCCESS';
export const CREATE_ROUTINE_FAILURE = 'TRAINER_CREATE_ROUTINE_FAILURE';

export const UPDATE_ROUTINE = 'TRAINER_UPDATE_ROUTINE';
export const UPDATE_ROUTINE_SUCCESS = 'TRAINER_UPDATE_ROUTINE_SUCCESS';
export const UPDATE_ROUTINE_FAILURE = 'TRAINER_UPDATE_ROUTINE_FAILURE';

export const DELETE_ROUTINE = 'TRAINER_DELETE_ROUTINE';
export const DELETE_ROUTINE_SUCCESS = 'TRAINER_DELETE_ROUTINE_SUCCESS';
export const DELETE_ROUTINE_FAILURE = 'TRAINER_DELETE_ROUTINE_FAILURE';

export const FETCH_STUDENT_ROUTINES = 'TRAINER_FETCH_STUDENT_ROUTINES';
export const FETCH_STUDENT_ROUTINES_SUCCESS = 'TRAINER_FETCH_STUDENT_ROUTINES_SUCCESS';
export const FETCH_STUDENT_ROUTINES_FAILURE = 'TRAINER_FETCH_STUDENT_ROUTINES_FAILURE';

export const SET_SELECTED_STUDENT = 'TRAINER_SET_SELECTED_STUDENT';
export const SET_SELECTED_ROUTINE = 'TRAINER_SET_SELECTED_ROUTINE';
